services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: Dudadb
      POSTGRES_PASSWORD: Duda123456
      POSTGRES_DB: nestdb
    ports:
    - "5432:5432"
