
# Etapa 01: Definir a imagem base do Node
FROM node:20-alpine

# Etapa 02: Definir o diretório de tarbalho do container
WORKDIR /app

#  Etapa 03: Copiar arquivos de dependência instalar
COPY package.json /.
COPY package-lock.json /.
# COPY package*.json /.
RUN npm install

# Etapa 04: Copiar o restante dos arquivos e compilar o projeto
COPY . .
RUN npx prisma generate
RUN npm run build

# Etapa 05: Expor a porta da aplicação 
EXPOSE 3000

